import type { DashboardRange, DashboardScenario } from "../../lib/models";

export const DASHBOARD_SEGMENTS = [
  { label: "Daily", value: "daily" },
  { label: "Weekly", value: "weekly" },
  { label: "Monthly", value: "monthly" },
] as const satisfies { label: string; value: DashboardRange }[];

export const DASHBOARD_FALLBACK_SCENARIOS: Record<
  DashboardRange,
  DashboardScenario
> = {
  daily: {
    eyebrow: "Daily read · FIT-backed preview",
    title: "March 22 run · 5.01 km loop",
    description:
      "This activity file contains 2,388 second-level records, 2,380 GPS points, six laps, heart rate, power, cadence, stride length, stance time, and vertical oscillation.",
    insightTitle: "The run stayed mechanically stable, but cardiovascular cost rose through the middle kilometers.",
    insight:
      "The first kilometer opened at 7:41/km and the third drifted to 8:08/km, while heart rate climbed from 154 bpm to the high 160s. Power stayed relatively narrow, which makes this a useful example of rising effort without a dramatic collapse in form.",
    keyStats: [
      { label: "Elapsed time", value: "39:48", delta: "2,388 records" },
      { label: "Average HR", value: "164 bpm", delta: "Peak 177 bpm" },
      { label: "Average power", value: "246 W", delta: "Peak 352 W" },
      { label: "Run form", value: "72.9 cm", delta: "7.3 cm vertical osc." },
    ],
    trendTitle: "Kilometer rhythm",
    trendCaption:
      "Primary line shows lap pace in minutes per kilometer. Accent line tracks average heart rate for the same kilometer split.",
    trend: [
      { label: "1Km", primary: 7.68, accent: 154 },
      { label: "2Km", primary: 7.91, accent: 164 },
      { label: "3Km", primary: 8.13, accent: 167 },
      { label: "4Km", primary: 7.85, accent: 168 },
      { label: "5Km", primary: 8.18, accent: 167 },
    ],
    ring: {
      value: 76,
      label: "Run economy",
      caption:
        "Stride length, stance time, and vertical oscillation stayed inside a tight band even as heart rate climbed, which suggests the slowdown was more cardiovascular than structural.",
    },
    distributionTitle: "Heart-rate zone share",
    distribution: [
      { label: "Z2", value: 1, tone: "#ffe2d5", detail: "opening seconds" },
      { label: "Z3", value: 3, tone: "#ffc2a8", detail: "brief settling period" },
      { label: "Z4", value: 82, tone: "#ff7b55", detail: "main steady effort" },
      { label: "Z5", value: 14, tone: "#cf4b2f", detail: "late-cardio strain" },
    ],
    activityTitle: "Per-kilometer breakdown",
    activityCaption:
      "The wide comparison strip now exposes the core lap fields from the FIT file directly, so each full kilometer can be scanned across cardio load, power, mechanics, terrain, and work.",
    activityHighlights: [
      { label: "Visible metrics", value: "12 per split", delta: "raw lap fields on screen" },
      { label: "Total strides", value: "3,411", delta: "across the 5 full-km laps" },
      { label: "Cumulative work", value: "588.1 kJ", delta: "excluding the micro-lap" },
      { label: "Hidden remainder", value: "1 micro-lap", delta: "post-5 km partial split" },
    ],
    activityColumns: [
      "Split",
      "Time",
      "Avg HR",
      "Max HR",
      "Avg power",
      "NP",
      "Max power",
      "Cadence",
      "Stride",
      "Strides",
      "Ground",
      "Vertical",
      "Terrain",
      "Work",
    ],
    activities: [
      {
        title: "1Km",
        date: "7:41",
        distance: "154 avg / 168 max",
        pace: "253 avg / 263 NP",
        effort: "275 ms · 9.68%",
        values: [
          "1Km",
          "7:41",
          "154",
          "168",
          "253 W",
          "263 W",
          "352 W",
          "86 avg · 90 max",
          "75.7 cm",
          "663",
          "275.5 ms",
          "7.3 cm · 9.68%",
          "+4 / -0 m",
          "116.6 kJ",
        ],
      },
      {
        title: "2Km",
        date: "7:54",
        distance: "164 avg / 171 max",
        pace: "248 avg / 249 NP",
        effort: "277 ms · 9.95%",
        values: [
          "2Km",
          "7:54",
          "164",
          "171",
          "248 W",
          "249 W",
          "321 W",
          "87 avg · 90 max",
          "71.5 cm",
          "691",
          "277.4 ms",
          "7.1 cm · 9.95%",
          "+3 / -4 m",
          "117.6 kJ",
        ],
      },
      {
        title: "3Km",
        date: "8:08",
        distance: "167 avg / 173 max",
        pace: "240 avg / 240 NP",
        effort: "282 ms · 10.18%",
        values: [
          "3Km",
          "8:08",
          "167",
          "173",
          "240 W",
          "240 W",
          "281 W",
          "86 avg · 89 max",
          "70.7 cm",
          "699",
          "282.1 ms",
          "7.2 cm · 10.18%",
          "+1 / -2 m",
          "117.0 kJ",
        ],
      },
      {
        title: "4Km",
        date: "7:51",
        distance: "168 avg / 177 max",
        pace: "248 avg / 249 NP",
        effort: "284 ms · 10.04%",
        values: [
          "4Km",
          "7:51",
          "168",
          "177",
          "248 W",
          "249 W",
          "275 W",
          "85 avg · 88 max",
          "74.7 cm",
          "667",
          "284.1 ms",
          "7.5 cm · 10.04%",
          "+1 / -3 m",
          "117.1 kJ",
        ],
      },
      {
        title: "5Km",
        date: "8:11",
        distance: "167 avg / 177 max",
        pace: "244 avg / 247 NP",
        effort: "287 ms · 10.28%",
        values: [
          "5Km",
          "8:11",
          "167",
          "177",
          "244 W",
          "247 W",
          "343 W",
          "84 avg · 89 max",
          "72.4 cm",
          "691",
          "286.8 ms",
          "7.4 cm · 10.28%",
          "+1 / -0 m",
          "119.8 kJ",
        ],
      },
    ],
    splitPanelsTitle: "Raw split inspector",
    splitPanelsCaption:
      "Each kilometer exposes the lap-level signals Garmin recorded in the FIT file: cardiac load, avg-plus-normalized power, turnover, stride shape, ground contact, terrain, work, and drift against the session baseline.",
    splitPanels: [
      {
        label: "1Km",
        headline: "Controlled opening with the cleanest mechanics",
        summary:
          "The opening kilometer paired the longest stride of the run with the shortest ground contact time, while heart rate stayed comfortably below the session peak.",
        time: "7:41",
        pace: "7:41 /km",
        note:
          "This was the most efficient-looking split in the file: long stride, short contact time, and power sitting above the session average without a matching spike in strain.",
        metrics: [
          { label: "Heart rate", value: "154 bpm", detail: "168 bpm peak" },
          { label: "Power", value: "253 W", detail: "263 NP · 352 W max" },
          { label: "Cadence", value: "86 avg · 90 max", detail: "spm" },
          { label: "Stride length", value: "75.7 cm", detail: "663 total strides" },
          { label: "Session delta", value: "HR -10 · PWR +7", detail: "+2.8 cm stride vs run avg" },
          { label: "Ground contact", value: "275.5 ms", detail: "Shortest split" },
          { label: "Mechanical drift", value: "-5.8 ms", detail: "-0.35 vertical ratio vs run avg" },
          { label: "Vertical motion", value: "7.3 cm", detail: "9.68% ratio" },
          { label: "Terrain", value: "+4 m / -0 m", detail: "Flat opener" },
          { label: "Work", value: "116.6 kJ", detail: "461 s timer" },
        ],
      },
      {
        label: "2Km",
        headline: "Effort stepped up while stride shortened",
        summary:
          "Heart rate rose by 10 bpm with only a small drop in average power, and stride length fell by more than 4 cm compared with the opening kilometer.",
        time: "7:54",
        pace: "7:54 /km",
        note:
          "The loop started costing more here: turnover stayed high, but shorter steps and a slightly longer contact time made the same output feel pricier.",
        metrics: [
          { label: "Heart rate", value: "164 bpm", detail: "171 bpm peak" },
          { label: "Power", value: "248 W", detail: "249 NP · 321 W max" },
          { label: "Cadence", value: "87 avg · 90 max", detail: "spm" },
          { label: "Stride length", value: "71.5 cm", detail: "691 total strides" },
          { label: "Session delta", value: "HR +0 · PWR +2", detail: "-1.4 cm stride vs run avg" },
          { label: "Ground contact", value: "277.4 ms", detail: "+1.9 ms vs Km 1" },
          { label: "Mechanical drift", value: "-3.9 ms", detail: "-0.08 vertical ratio vs run avg" },
          { label: "Vertical motion", value: "7.1 cm", detail: "9.95% ratio" },
          { label: "Terrain", value: "+3 m / -4 m", detail: "Rolling middle section" },
          { label: "Work", value: "117.6 kJ", detail: "474 s timer" },
        ],
      },
      {
        label: "3Km",
        headline: "Cardio drift peaked in the slowest split",
        summary:
          "The third kilometer was the slowest at 8:08/km, with the shortest stride of the run and one of the highest average heart-rate readings.",
        time: "8:08",
        pace: "8:08 /km",
        note:
          "Mechanics were still tidy enough to avoid collapse, but each stride covered less ground while heart rate kept climbing, which is why this reads as the costliest kilometer.",
        metrics: [
          { label: "Heart rate", value: "167 bpm", detail: "173 bpm peak" },
          { label: "Power", value: "240 W", detail: "240 NP · 281 W max" },
          { label: "Cadence", value: "86 avg · 89 max", detail: "spm" },
          { label: "Stride length", value: "70.7 cm", detail: "699 total strides" },
          { label: "Session delta", value: "HR +3 · PWR -6", detail: "-2.3 cm stride vs run avg" },
          { label: "Ground contact", value: "282.1 ms", detail: "First split above 282 ms" },
          { label: "Mechanical drift", value: "+0.8 ms", detail: "+0.15 vertical ratio vs run avg" },
          { label: "Vertical motion", value: "7.2 cm", detail: "10.18% ratio" },
          { label: "Terrain", value: "+1 m / -2 m", detail: "Mostly flat" },
          { label: "Work", value: "117.0 kJ", detail: "488 s timer" },
        ],
      },
      {
        label: "4Km",
        headline: "Best rebound after the mid-run fade",
        summary:
          "Stride bounced back to 74.7 cm and the split sharpened to 7:51/km even though heart rate touched the session max of 177 bpm.",
        time: "7:51",
        pace: "7:51 /km",
        note:
          "This is the clearest recovery kilometer in the file: longer steps restored pace without demanding dramatically more power, even with late-run cardiovascular stress rising.",
        metrics: [
          { label: "Heart rate", value: "168 bpm", detail: "177 bpm peak" },
          { label: "Power", value: "248 W", detail: "249 NP · 275 W max" },
          { label: "Cadence", value: "85 avg · 88 max", detail: "spm" },
          { label: "Stride length", value: "74.7 cm", detail: "667 total strides" },
          { label: "Session delta", value: "HR +4 · PWR +2", detail: "+1.8 cm stride vs run avg" },
          { label: "Ground contact", value: "284.1 ms", detail: "Late-run loading" },
          { label: "Mechanical drift", value: "+2.8 ms", detail: "+0.01 vertical ratio vs run avg" },
          { label: "Vertical motion", value: "7.5 cm", detail: "10.04% ratio" },
          { label: "Terrain", value: "+1 m / -3 m", detail: "Slight downhill help" },
          { label: "Work", value: "117.1 kJ", detail: "471 s timer" },
        ],
      },
      {
        label: "5Km",
        headline: "Late fatigue with power held and economy slipping",
        summary:
          "Average power stayed close to the session mean, but cadence dropped to its lowest point and ground contact stretched to the highest mark of the run.",
        time: "8:11",
        pace: "8:11 /km",
        note:
          "The last full kilometer shows classic fatigue markers: slightly lower turnover, longer time on the ground, and the highest vertical ratio despite power remaining reasonably steady.",
        metrics: [
          { label: "Heart rate", value: "167 bpm", detail: "177 bpm peak" },
          { label: "Power", value: "244 W", detail: "247 NP · 343 W max" },
          { label: "Cadence", value: "84 avg · 89 max", detail: "spm" },
          { label: "Stride length", value: "72.4 cm", detail: "691 total strides" },
          { label: "Session delta", value: "HR +3 · PWR -2", detail: "-0.6 cm stride vs run avg" },
          { label: "Ground contact", value: "286.8 ms", detail: "Longest split" },
          { label: "Mechanical drift", value: "+5.5 ms", detail: "+0.25 vertical ratio vs run avg" },
          { label: "Vertical motion", value: "7.4 cm", detail: "10.28% ratio" },
          { label: "Terrain", value: "+1 m / -0 m", detail: "Flat finish" },
          { label: "Work", value: "119.8 kJ", detail: "491 s timer" },
        ],
      },
    ],
    notesTitle: "What this file tells us",
    notes: [
      "The raw FIT file carries 2,380 usable GPS points, which means the route panel can become a real trace instead of a decorative placeholder.",
      "Heart rate spent 82% of the timer time in Z4 and another 14% in Z5, making this a much harder effort than the pace alone suggests.",
      "Average stance time stayed near 281 ms and average vertical ratio near 10.03, which is enough biomechanical signal to justify a dedicated running-form section.",
      "The FIT file also contains a sixth micro-lap after 5 km; the dashboard intentionally hides it so the split view stays aligned to complete kilometers.",
    ],
    routePoints: [
      { x: 0.2096, y: 0.1617 },
      { x: 0.2644, y: 0.2152 },
      { x: 0.3208, y: 0.2622 },
      { x: 0.3764, y: 0.3074 },
      { x: 0.4301, y: 0.3519 },
      { x: 0.4850, y: 0.3963 },
      { x: 0.5374, y: 0.4362 },
      { x: 0.5859, y: 0.4764 },
      { x: 0.6360, y: 0.5151 },
      { x: 0.6822, y: 0.5788 },
      { x: 0.7290, y: 0.6452 },
      { x: 0.7714, y: 0.7177 },
      { x: 0.8176, y: 0.7862 },
      { x: 0.8679, y: 0.8534 },
      { x: 0.9179, y: 0.9195 },
      { x: 0.9627, y: 0.9728 },
      { x: 0.9996, y: 0.9610 },
      { x: 0.9850, y: 0.8446 },
      { x: 0.9333, y: 0.8252 },
      { x: 0.8807, y: 0.7879 },
      { x: 0.8313, y: 0.7522 },
      { x: 0.7837, y: 0.7166 },
      { x: 0.7388, y: 0.6686 },
      { x: 0.6948, y: 0.6001 },
      { x: 0.6505, y: 0.5301 },
      { x: 0.6005, y: 0.4870 },
      { x: 0.5529, y: 0.4516 },
      { x: 0.5004, y: 0.4115 },
      { x: 0.4438, y: 0.3643 },
      { x: 0.3925, y: 0.3231 },
      { x: 0.3403, y: 0.2791 },
      { x: 0.2884, y: 0.2363 },
      { x: 0.2379, y: 0.1949 },
      { x: 0.1861, y: 0.1573 },
      { x: 0.1352, y: 0.1273 },
      { x: 0.0852, y: 0.0902 },
      { x: 0.0407, y: 0.0460 },
      { x: 0.0018, y: 0.0022 },
      { x: 0.0448, y: 0.0493 },
      { x: 0.0903, y: 0.0916 },
    ],
    geoRoutePoints: [
      { latitude: 37.537077, longitude: 127.045403 },
      { latitude: 37.536606, longitude: 127.046818 },
      { latitude: 37.536193, longitude: 127.048279 },
      { latitude: 37.535796, longitude: 127.049715 },
      { latitude: 37.535404, longitude: 127.051105 },
      { latitude: 37.535014, longitude: 127.052524 },
      { latitude: 37.534662, longitude: 127.053879 },
      { latitude: 37.534309, longitude: 127.055132 },
      { latitude: 37.533969, longitude: 127.056429 },
      { latitude: 37.533409, longitude: 127.057623 },
      { latitude: 37.532825, longitude: 127.058835 },
      { latitude: 37.532188, longitude: 127.059932 },
      { latitude: 37.531585, longitude: 127.061125 },
      { latitude: 37.530995, longitude: 127.062426 },
      { latitude: 37.530413, longitude: 127.06372 },
      { latitude: 37.529945, longitude: 127.064879 },
      { latitude: 37.530048, longitude: 127.065831 },
      { latitude: 37.531071, longitude: 127.065455 },
      { latitude: 37.531243, longitude: 127.064119 },
      { latitude: 37.531571, longitude: 127.062758 },
      { latitude: 37.531884, longitude: 127.061481 },
      { latitude: 37.532198, longitude: 127.06025 },
      { latitude: 37.53262, longitude: 127.059087 },
      { latitude: 37.533222, longitude: 127.057951 },
      { latitude: 37.533838, longitude: 127.056803 },
      { latitude: 37.534217, longitude: 127.055511 },
      { latitude: 37.534528, longitude: 127.054279 },
      { latitude: 37.53488, longitude: 127.052923 },
      { latitude: 37.535295, longitude: 127.05146 },
      { latitude: 37.535657, longitude: 127.050133 },
      { latitude: 37.536044, longitude: 127.048782 },
      { latitude: 37.536421, longitude: 127.04744 },
      { latitude: 37.536785, longitude: 127.046133 },
      { latitude: 37.537115, longitude: 127.044794 },
      { latitude: 37.537379, longitude: 127.043478 },
      { latitude: 37.537705, longitude: 127.042184 },
      { latitude: 37.538094, longitude: 127.041034 },
      { latitude: 37.538479, longitude: 127.040028 },
      { latitude: 37.538065, longitude: 127.04114 },
      { latitude: 37.537693, longitude: 127.042318 },
    ],
  },
  weekly: {
    eyebrow: "Weekly review",
    title: "Week of March 23, 2026",
    description:
      "Track weekly volume, workout mix, and how evenly the training load was spread across the week.",
    insightTitle: "Mileage was balanced, but intensity stacked on back-to-back days.",
    insight:
      "The total volume is healthy and the long run stayed under control, yet two moderate-to-hard sessions landed too close together. A slightly calmer Thursday would likely improve weekend sharpness.",
    keyStats: [
      { label: "Distance", value: "68.7 km", delta: "+9% vs previous week" },
      { label: "Time on feet", value: "5h 48m", delta: "+22 min vs previous week" },
      { label: "Runs", value: "6 sessions", delta: "1 rest day" },
      { label: "Long run", value: "22.1 km", delta: "Negative split finish" },
    ],
    trendTitle: "Volume by day",
    trendCaption:
      "Primary line shows distance. Accent line tracks average effort across the same days.",
    trend: [
      { label: "Mon", primary: 8.2, accent: 4.1 },
      { label: "Tue", primary: 12.4, accent: 7.2 },
      { label: "Wed", primary: 9.8, accent: 5.2 },
      { label: "Thu", primary: 11.2, accent: 6.9 },
      { label: "Fri", primary: 0.0, accent: 1.2 },
      { label: "Sat", primary: 5.0, accent: 3.8 },
      { label: "Sun", primary: 22.1, accent: 6.3 },
    ],
    ring: {
      value: 71,
      label: "Weekly balance",
      caption:
        "The workload is productive overall, but redistributing one medium-hard day would create a steadier rhythm through the week.",
    },
    distributionTitle: "Workout mix",
    distribution: [
      { label: "Easy", value: 42, tone: "#ffd6cb", detail: "base-building volume" },
      { label: "Steady", value: 26, tone: "#ffb59f", detail: "moderate aerobic work" },
      { label: "Threshold", value: 20, tone: "#ff6a48", detail: "tempo and cruise reps" },
      { label: "Long run", value: 12, tone: "#cb4026", detail: "extended endurance" },
    ],
    activityTitle: "Key sessions this week",
    activities: [
      { title: "Tuesday tempo", date: "Mar 24", distance: "12.4 km", pace: "4:36", effort: "High quality" },
      { title: "Thursday hills", date: "Mar 26", distance: "11.2 km", pace: "4:58", effort: "Muscular" },
      { title: "Sunday long run", date: "Mar 29", distance: "22.1 km", pace: "5:11", effort: "Controlled" },
      { title: "Saturday shakeout", date: "Mar 28", distance: "5.0 km", pace: "5:34", effort: "Very easy" },
    ],
    notesTitle: "Weekly coaching notes",
    notes: [
      "The week shows strong consistency, especially with only one full rest day.",
      "Thursday's hill session created fatigue that was still visible on Saturday morning.",
      "The long run pace sat in a sustainable range and did not compromise recovery markers.",
    ],
  },
  monthly: {
    eyebrow: "Monthly review",
    title: "March 2026 progression",
    description:
      "Step back and review cumulative volume, consistency, and whether the month created meaningful progression without hidden overload.",
    insightTitle: "The month built cleanly around long-run durability.",
    insight:
      "Long-run frequency stayed reliable, total distance progressed smoothly, and the best efforts improved without a sudden spike in strain. That is the pattern worth repeating into the next block.",
    keyStats: [
      { label: "Distance", value: "212 km", delta: "+14% vs February" },
      { label: "Runs", value: "18 sessions", delta: "4.5 per week" },
      { label: "Longest run", value: "28.0 km", delta: "+3 km monthly peak" },
      { label: "Best 10K", value: "42:18", delta: "Season best" },
    ],
    trendTitle: "Weekly mileage across the month",
    trendCaption:
      "Primary line shows weekly mileage. Accent line tracks perceived freshness across each week.",
    trend: [
      { label: "W1", primary: 44.3, accent: 7.1 },
      { label: "W2", primary: 49.8, accent: 6.8 },
      { label: "W3", primary: 56.2, accent: 6.4 },
      { label: "W4", primary: 61.7, accent: 6.2 },
    ],
    ring: {
      value: 83,
      label: "Block quality",
      caption:
        "The month reads as productive rather than rushed. Volume growth stayed progressive and performance improved without obvious breakdown markers.",
    },
    distributionTitle: "Terrain and effort mix",
    distribution: [
      { label: "Flat aerobic", value: 38, tone: "#ffd6cb", detail: "steady base mileage" },
      { label: "Rolling terrain", value: 22, tone: "#ffb59f", detail: "strength through variety" },
      { label: "Workout quality", value: 24, tone: "#ff6a48", detail: "tempos and intervals" },
      { label: "Long endurance", value: 16, tone: "#cb4026", detail: "weekend durability" },
    ],
    activityTitle: "Monthly signature sessions",
    activities: [
      { title: "Long run peak", date: "Mar 16", distance: "28.0 km", pace: "5:08", effort: "Even and strong" },
      { title: "10K best effort", date: "Mar 19", distance: "10.0 km", pace: "4:14", effort: "Season best" },
      { title: "Cruise intervals", date: "Mar 11", distance: "13.6 km", pace: "4:31", effort: "Locked in" },
      { title: "Recovery week opener", date: "Mar 3", distance: "7.2 km", pace: "5:39", effort: "Reset" },
    ],
    notesTitle: "Month-end takeaways",
    notes: [
      "Long-run rhythm became the strongest repeating signal in the training block.",
      "The best-effort 10K suggests threshold work is converting into race-specific pace.",
      "April should preserve the long-run backbone while adding one carefully measured sharpening session.",
    ],
    heatmapTitle: "Run density calendar",
    heatmap: [
      { label: "Mar 1", value: 6, level: 1 },
      { label: "Mar 2", value: 0, level: 0 },
      { label: "Mar 3", value: 7, level: 2 },
      { label: "Mar 4", value: 11, level: 3 },
      { label: "Mar 5", value: 0, level: 0 },
      { label: "Mar 6", value: 8, level: 1 },
      { label: "Mar 7", value: 18, level: 4 },
      { label: "Mar 8", value: 5, level: 1 },
      { label: "Mar 9", value: 0, level: 0 },
      { label: "Mar 10", value: 9, level: 2 },
      { label: "Mar 11", value: 14, level: 3 },
      { label: "Mar 12", value: 0, level: 0 },
      { label: "Mar 13", value: 10, level: 2 },
      { label: "Mar 14", value: 22, level: 4 },
      { label: "Mar 15", value: 8, level: 1 },
      { label: "Mar 16", value: 28, level: 5 },
      { label: "Mar 17", value: 0, level: 0 },
      { label: "Mar 18", value: 9, level: 2 },
      { label: "Mar 19", value: 10, level: 3 },
      { label: "Mar 20", value: 0, level: 0 },
      { label: "Mar 21", value: 7, level: 1 },
      { label: "Mar 22", value: 16, level: 4 },
      { label: "Mar 23", value: 8, level: 1 },
      { label: "Mar 24", value: 12, level: 3 },
      { label: "Mar 25", value: 10, level: 2 },
      { label: "Mar 26", value: 11, level: 2 },
      { label: "Mar 27", value: 0, level: 0 },
      { label: "Mar 28", value: 5, level: 1 },
      { label: "Mar 29", value: 22, level: 4 },
      { label: "Mar 30", value: 0, level: 0 },
      { label: "Mar 31", value: 8, level: 1 },
      { label: "Apr 1", value: 0, level: 0 },
      { label: "Apr 2", value: 0, level: 0 },
      { label: "Apr 3", value: 0, level: 0 },
      { label: "Apr 4", value: 0, level: 0 },
    ],
  },
};
